[package]
name = "KTH-Thesis"
version = "0.1.0"
authors = ["Johan Vikstr√∂m <johan.vikstrom7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
